version: '2'
services:
  riot-web:
    image: kalaksi/riot-web
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    volumes:
      - riotweb_config:/opt/riot-web/config.json:ro
    ports:
      - 80:8080/tcp

volumes:
  riotweb_config: {}
